name: CornellTours
version: @version@
main: dev.faizaan.cornelltours.CornellTours
api-version: 1.16
#depend: [NPCLib]
authors: [FaizaanDatoo]
description: Guided tours plugin for CornellCraft virtual tours.
website: https://faizaan.dev
commands:
  tour:
    description: Start a new tour.
    permission: cornelltours.default
  endtour:
    description: Ends your active tour.
    permission: cornelltours.default
  destination:
    description: Administrative commands for tour destinations.
    permission: cornelltours.admin
